name: Markdown Lint

on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    branches:
      - master
    paths:
      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Markdown Lint Check
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history for better git operations
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: |
          npm install --global markdownlint-cli2
          npm install --global prettier

      - name: Run markdownlint
        run: |
          markdownlint-cli2 "**/*.md" "#node_modules" "#src/thirdparty" "#.git"

      - name: Check trailing whitespace and tabs
        run: |
          echo "Checking for trailing whitespace and tabs in markdown files..."
          # Create a simple check for trailing whitespace
          violations_found=0
          for file in $(find . -name "*.md" -not -path "./node_modules/*" -not -path "./src/thirdparty/*" -not -path "./.git/*"); do
            if grep -q '[[:space:]]$' "$file"; then
              echo "❌ Found trailing whitespace in: $file"
              violations_found=1
            fi
          done
          
          if [ $violations_found -eq 1 ]; then
            echo "ERROR: Found trailing whitespace in markdown files"
            exit 1
          else
            echo "✅ No trailing whitespace found"
          fi

      - name: Check line length (practical limit: 100 chars)
        run: |
          echo "Checking line length in markdown files..."
          violations_found=0
          while IFS= read -r -d '' file; do
            long_lines=$(grep -n '.\{101\}' "$file" | grep -v -E '^\s*\|.*\|.*\|' | grep -v -E '^\s*\[.*\]:.*http' | head -5)
            if [ -n "$long_lines" ]; then
              echo "Long lines in $file:"
              echo "$long_lines"
              violations_found=1
            fi
          done < <(find . -name "*.md" \
            -not -path "./node_modules/*" \
            -not -path "./src/thirdparty/*" \
            -not -path "./.git/*" \
            -print0)
          
          if [ $violations_found -eq 1 ]; then
            echo "ERROR: Found lines longer than 100 characters (excluding tables and URLs)"
            exit 1
          else
            echo "All lines are within the 100-character limit"
          fi

      - name: Report success
        if: success()
        run: |
          echo "✅ All markdown lint checks passed!"
          echo "- Header order: correct"
          echo "- No trailing whitespace/tabs"
          echo "- Line length: ≤ 100 characters (where practical)"
